### ISSUE TITLE
/api/ is missing

### ISSUE THREAD

**Issue by sithglan** [NetAppDocs/ontap-restapi#15] opened 2024-05-04 14:32 UTC
### Page URL

https://docs.netapp.com/us-en/ontap-restapi/ontap/get-cluster-nodes.html

### Page title

Retrieve the nodes in a cluster

### Summary

Hello,
the api endpoint misses the '/api/' part.
wrong: GET /cluster/nodes
right: GET /api/cluster/nodes

Tested on ontap 9.14.1P2

Cheers,
    Thomas

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-pcarriga** [comment] 2024-05-08 15:26
Thank you for highlighting the issue. We'll investigate and fix as soon as possible.

**Comment by netapp-aoife** [comment] 2024-07-30 09:30
Hi @sithglan thanks again for raising this. Closing this as the issue is being tracked internally for further investigation with ONTAP engineering.

**Closed by netapp-aoife** 2024-07-30 09:30 UTC
