### ISSUE TITLE
/api/ seems to be missing on a lot of documentation pages

### ISSUE THREAD

**Issue by sithglan** [NetAppDocs/ontap-restapi#16] opened 2024-05-04 15:08 UTC
### Page URL

https://docs.netapp.com/us-en/ontap-restapi/ontap/get-snapmirror-relationships-.html

### Page title

Retrieve a SnapMirror relationship

### Summary

Hello,
I saw that /api/ is missing in a lot of documentation pages for the rest API.
WRONG: GET /snapmirror/relationships/{uuid}
Right:  GET /api/snapmirror/relationships/{uuid}

Cheers,
     Thomas

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-pcarriga** [comment] 2024-05-08 15:26
Thank you for highlighting the issue. We'll investigate and fix as soon as possible.

**Comment by netapp-aoife** [comment] 2024-07-30 09:29
Hi @sithglan thanks again for raising this. Closing this as the issue is being tracked internally for further investigation with ONTAP engineering.

**Closed by netapp-aoife** 2024-07-30 09:29 UTC
